title: Trump es   reptiliano
description:  Hola que aze.
permalink: ':title/'
baseurl: "/" 
url: "https://canvas2017.github.io" 


author: Sé más que un blogger  
author-img: logo-pie.png  
about-author: odio a Peppa Pig ,Caillou y Pocoyo.

